### ISSUE TITLE
Tensorflow Dependency Issues

### ISSUE THREAD

**Issue by MarkProjectRepo** [jrgillick/laughter-detection#10]
Hey there,

I'm curious what version of tensorflow you're running alongside your keras dependency, as when I follow your requirements I receive the following error when trying to run the segment_laughter.py file:

> Traceback (most recent call last):
  File "segment_laughter.py", line 3, in <module>
    import laugh_segmenter
  File "/home/mark/work/work/voice/laughterdetection/laugh_segmenter.py", line 2, in <module>
    config = tf.ConfigProto()
AttributeError: module 'tensorflow' has no attribute 'ConfigProto'

**Comment by MarkProjectRepo** [comment]
Worth noting that this is an issue from tensorflow 1.* to 2.* , just curious what version of 1.* you are on

**Comment by MarkProjectRepo** [comment]
Solved this issue either by downgrading to tensorflow 1.35;
